import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { TrendingDown, Calendar, Layers, Copy, Check, ExternalLink, ArrowLeft, Loader2 } from "lucide-react";
import API from "../services/api";

const ShareReport = () => {
  const { shareId } = useParams();
  const [audit, setAudit] = useState(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetchAudit();
  }, []);

  const fetchAudit = async () => {
    try {
      const res = await API.get(`/audit/share/${shareId}`);
      setAudit(res.data.audit);
    } catch {
      console.error("Failed to fetch shared audit");
    }
    setLoading(false);
  };

  const copyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-white">
        <Loader2 size={22} className="animate-spin text-gray-300" />
      </div>
    );
  }

  if (!audit) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-white text-gray-900">
        <p className="text-gray-400">This audit report could not be found.</p>
        <Link
          to="/"
          className="flex items-center gap-1.5 text-sm font-medium text-gray-900 underline underline-offset-2 hover:text-gray-600"
        >
          <ArrowLeft size={13} /> Run your own audit
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 px-6 py-16 text-gray-900">
      <div className="mx-auto max-w-3xl">

        {/* Header */}
        <div className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-gray-200 bg-white px-4 py-1.5 text-[11px] font-semibold uppercase tracking-[0.2em] text-gray-500">
            <Layers size={10} />
            Shared Audit Report
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900">
            AI Spend Audit Results
          </h1>
          <p className="mt-3 text-sm text-gray-400">
            Generated by SpendLens · Powered by Credex pricing data
          </p>
        </div>

        {/* Main stats */}
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="rounded-2xl border border-gray-200 bg-white p-6">
            <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.2em] text-gray-400">
              <TrendingDown size={11} />
              Monthly Savings
            </div>
            <p className="mt-4 text-5xl font-bold tracking-tight text-gray-900">
              ${audit.totalMonthlySavings?.toLocaleString()}
              <span className="ml-1 text-xl font-normal text-gray-300">/mo</span>
            </p>
          </div>
          <div className="rounded-2xl border border-gray-200 bg-white p-6">
            <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.2em] text-gray-400">
              <Calendar size={11} />
              Annual Savings
            </div>
            <p className="mt-4 text-5xl font-bold tracking-tight text-gray-900">
              ${audit.totalAnnualSavings?.toLocaleString()}
            </p>
          </div>
        </div>

        {/* Use case */}
        {audit.useCase && (
          <div className="mt-4 rounded-2xl border border-gray-200 bg-white px-5 py-4">
            <p className="text-sm text-gray-500">
              <span className="font-semibold text-gray-900">Use case:</span> {audit.useCase}
            </p>
          </div>
        )}

        {/* Tool breakdown */}
        {audit.recommendations?.length > 0 && (
          <div className="mt-8">
            <p className="mb-4 text-[11px] font-semibold uppercase tracking-[0.2em] text-gray-400">
              Tool-by-Tool Breakdown
            </p>
            <div className="space-y-2">
              {audit.recommendations.map((item, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between rounded-xl border border-gray-100 bg-white px-5 py-4 transition hover:border-gray-200"
                >
                  <div>
                    <p className="text-sm font-semibold text-gray-900">{item.tool}</p>
                    {item.plan && <p className="text-xs text-gray-400">{item.plan}</p>}
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-bold text-green-600">-${item.savings}/mo</p>
                    <p className="text-xs text-gray-400">${item.currentSpend} → ${item.recommendedSpend}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CTA */}
        <div className="mt-8 rounded-2xl border border-gray-200 bg-white p-8 text-center">
          <p className="text-lg font-bold text-gray-900">Want to see your own AI spend audit?</p>
          <p className="mt-1.5 text-sm text-gray-400">Free, instant, no login required.</p>
          <Link
            to="/"
            className="mt-5 inline-flex items-center gap-2 rounded-full bg-gray-900 px-6 py-3 text-sm font-semibold text-white transition hover:bg-gray-700"
          >
            <ExternalLink size={13} />
            Run My Free Audit
          </Link>
        </div>

        {/* Copy link */}
        <div className="mt-6 flex justify-center">
          <button
            onClick={copyLink}
            className="flex items-center gap-2 rounded-full border border-gray-200 bg-white px-4 py-2.5 text-sm font-medium text-gray-500 transition hover:border-gray-400 hover:text-gray-900"
          >
            {copied ? <Check size={13} className="text-green-500" /> : <Copy size={13} />}
            {copied ? "Link copied!" : "Copy shareable link"}
          </button>
        </div>

      </div>
    </div>
  );
};

export default ShareReport;